services:
  - type: web
    name: F.R.I.E.N.D.S
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://zbmfruntrdeyyxjnvhiy.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: sb_secret_IFDdd9ZGcKl3yVLQPvkKeg_Za9_HWaZ
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgres://postgres.zbmfruntrdeyyxjnvhiy:FriendsInfo%401361e@aws-1-eu-north-1.pooler.supabase.com:6543/postgres
      - key: TG_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
